<?php
session_start();
$heroname = $_SESSION["heroName"];
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice">
<main>
    <section>
        <h2>Bonjour valeureux héro <?php echo $heroname; ?></h2>
        <div>
            <form method="get" action="">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="choice-1">Epée</label>
                </div>
                <div>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                    <label for="choice-1">Arc</label>
                </div>
                <div>
                    <input type="radio" id="choice-3" name="choice" value="choice-3">
                    <label for="choice-1">Potion (attention)</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/door.png" />
            <h1>Vous vous trouvez dans un prison, seul. Vous observez devant vous trois objet que vous avez du mal à discerner. Vous vous approchez. Vous voyez une <span>épée</span>, <span>un arc</span>, et une <span>potion</span> de couleur bleu. Vous ne pouvez en choisir qu'un. Que décidez vous de choisir ?</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>