<?php
if ($_SERVER["REQUEST_METHOD"] == "GET") {
    if (isset($_GET["choice"]) && !empty($_GET["choice"])) {
        $choix_arme = $_GET["choice"];
        var_dump($choix_arme); 

        if ($choix_arme == "Epée") {
            header("Location: choice_epee.phtml");
            exit();
        } elseif ($choix_arme == "Arc") {
            header("Location: choice_arc.phtml");
            exit();
        } elseif ($choix_arme == "Potion") {
            header("Location: choice_potion.phtml");
            exit();
        }
    }
}
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<body id="choice">
<main>
    <section>
        <h2>Une âme d'acher, alors ? Allez vous en faire bon usage ?</h2>
        <div>
            <form method="get" action="">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="choice-1">J'essaie tant bien que mal de récuperer les flèches en utilisant mon arc</label>
                </div>
                <div>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                    <label for="choice-1">J'empoigne fermement mon arc et je mattraque le barreau.</label>
                </div>
                <div>
                    <input type="radio" id="choice-3" name="choice" value="choice-3">
                    <label for="choice-1">Impossible, je change d'arme.</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/bow.png" />
            <h1>Vous decouvrez en vous retournant un barreau fêlé. Vous apercevez juste derrière, un carquant rempli de flèches. L'arc à la main, que décidez vous de faire ?</h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>